CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table IF NOT EXISTS item_request
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL
    constraint request_pk
                primary key,
    description  varchar(200),
    requester_id bigint
        constraint item_request_users_id_fk
            references users,
    created      timestamp
);

create table IF NOT EXISTS item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        constraint item_pk
            primary key,
    owner_id    bigint
        constraint item_users_id_fk
            references users,
    name        varchar(100),
    description varchar(200) NOT NULL,
    available   boolean NOT NULL,
    request_id  bigint
    constraint item_request_id_fk
                references item_request
);

create table IF NOT EXISTS booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        constraint booking_pk
            primary key,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    bigint
        constraint booking_item_id_fk
            references item,
    booker_id  bigint
        constraint booking_users_id_fk
            references users,
    status varchar(8) NOT NULL
);

create table IF NOT EXISTS comment(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        constraint comment_pk
            primary key,
    text      varchar(200),
    item_id   BIGINT
        constraint comment_item_id_fk
            references item,
    author_id BIGINT
        constraint comment_users_id_fk
            references users,
    created   timestamp
);

